services:
  app:
    image: 'earnlike55/save-for-future:latest'
    ports:
      - 8082:8084
    build:
      context: .
    container_name: app
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/testdb
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=EarnEarn55
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update


  db:
    image: 'postgres:13.3-alpine'
    container_name: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=EarnEarn55
      - POSTGRES_DB=testdb